version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: "Call to rancher to deploy"
          command: |
              docker run --rm -it \
                -e CATTLE_ACCESS_KEY="$CATTLE_ACCESS_KEY" \
                -e CATTLE_SECRET_KEY="$CATTLE_SECRET_KEY" \
                -e CATTLE_URL="$CATTLE_URL" \
                etlweather/gaucho upgrade $RANCHER_EXAMPLE_NODEJS \
                --imageUuid 'docker:snoiyoo/example-nodejs-express:latest' \
                --batch_size 3 --start_first \
                --auto_complete --timeout 600 \
                /
    step:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json"}}
            - v1-dependencies-
      - run: cd example_worker
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: "Build docker image and push to docker hub" 
          command: |
            if ["${CIRCLE_BRANCH}"== "master"]; then
              docker build -t ima8/code_mania_demo:latest .
              docker build -t ima8/code_mania_demo:${CIRCLE_SHA1} .
              docker push ima8/code_mania_demo:latest
              docker push ima8/code_mania_demo:${CIRCLE_SHA1}
            elif ["${CIRCLE_BRANCH}"== "stagin"]; then
              docker build -t ima8/code_mania_demo_staging:latest .
              docker push ima8/code_mania_demo_staging:latest
            else
              echo "This is ${CIRCLE_BRANCH}"
            fi              
           
           
      
